---
- name: Kali System Setup Playbook
  hosts: all
  become: true
  become_method: sudo
  roles:
    - role: petermosmans.customize-gnome
  vars:
    gnome_dconf:
      - key: /org/gnome/desktop/background/show-desktop-icons
        value: "false"
    gnome_extensions:
      - url: https://extensions.gnome.org/download-extension/hidetopbar@mathieu.bidon.ca.shell-extension.zip?version_tag=6450
        name: hidetopbar@mathieu.bidon.ca
    gnome_fonts:
      - url: https://github.com/adobe-fonts/source-code-pro/archive/2.030R-ro/1.050R-it.zip
        name: SourceCodePro
        fonts: "source-code-pro-2.030R-ro-1.050R-it/OTF/*.otf"
    gnome_gsettings:
      - schema: org.gnome.desktop.interface
        key: monospace-font-name
        value: '"Source Code Pro Medium 16"'
      - schema: org.gnome.shell.extensions.dash-to-panel
        schemadir: ~/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/schemas
        key: panel-position
        value: BOTTOM
  tasks:

    # Update the apt cache
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    # Install packages
    - name: Install apt packages
      ansible.builtin.apt:
        name:
          - python3
          - python3-pip
          - python3-venv
          - seclists
          - curl
          - enum4linux
          - feroxbuster
          - gobuster
          - impacket-scripts
          - nbtscan
          - nmap
          - onesixtyone
          - oscanner
          - redis-tools
          - smbclient
          - smbmap
          - snmp
          - sslscan
          - sipvicious
          - tnscmd10g
          - whatweb
          - wkhtmltopdf
          - snapd
          - git
          - node-typescript
          - make
        state: present

    # Install Golang
    - name: Get lastest Go version
      ansible.builtin.shell: curl -sL https://golang.org/dl/?mode=json | sed 's/[][]//g' | awk '/version/ { print $2 }' | cut -d '"' -f2 | head -n1
      register: latest_go_version
      changed_when: false

    - name: Download Go tarball
      ansible.builtin.get_url:
        url: "https://golang.org/dl/{{ latest_go_version.stdout }}.linux-amd64.tar.gz"
        dest: "/tmp/{{ latest_go_version.stdout }}.linux-amd64.tar.gz"

    - name: Extract Go tarball
      ansible.builtin.unarchive:
        src: "/tmp/{{ latest_go_version.stdout }}.linux-amd64.tar.gz"
        dest: /usr/local
        extra_opts: [--strip-components=1]
        creates: /usr/local/go

    - name: Add Go to PATH
      ansible.builtin.lineinfile:
        path: /home/{{ ansible_user }}/.zshrc
        line: 'export PATH=$PATH:/usr/local/go/bin'
        create: true
        state: present
      become: false
